### ISSUE TITLE
Custom prefix and suffix not displaying for orders, invoices, credits and shipments

### ISSUE THREAD

**Issue by webcrew-au** [augustash/magento2-module-sales-sequence-customordernumber#1]
Hi thanks for posting your extension,

I've installed your extension and it works for the number length (0 padding) but does not append and prepend the values i've defined for prefix "ABC{mm}{dd}-" and sufix "-I"

Im using Magento 2.1.6.

Any idea's why?

**Comment by pawelcit** [comment]
Hi,

The same problem in Magento 2.2.2

**Comment by grafikchaos** [comment]
Sorry! I've had my head buried down in a project for a while. I'll take a look as soon as I can. Thanks for the report and the examples.

**Comment by ceymoxdev** [comment]
@grafikchaos Did you fix this issue

**Comment by grafikchaos** [comment]
@ceymoxdev - No, we moved onto another module to control the sequences as this module is no longer supported. I believe our fix to this problem was to manually update the database table.

**Comment by ceymoxdev** [comment]
@grafikchaos The new sequence control module is available on github ? if yes can i get the url please

**Comment by grafikchaos** [comment]
@ceymoxdev - sorry but the new module we use is a private repository.
